//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrecisionGazeMouse.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("world")]
        public string hello {
            get {
                return ((string)(this["hello"]));
            }
            set {
                this["hello"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool zoomboxEnabled {
            get {
                return ((bool)(this["zoomboxEnabled"]));
            }
            set {
                this["zoomboxEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cursorMagnetEnabled {
            get {
                return ((bool)(this["cursorMagnetEnabled"]));
            }
            set {
                this["cursorMagnetEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int cursorMagnetClippingThresholdMm {
            get {
                return ((int)(this["cursorMagnetClippingThresholdMm"]));
            }
            set {
                this["cursorMagnetClippingThresholdMm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int cursorMagnetClippingExitThresholdMm {
            get {
                return ((int)(this["cursorMagnetClippingExitThresholdMm"]));
            }
            set {
                this["cursorMagnetClippingExitThresholdMm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int cursorMagnetClippingExitDurationMs {
            get {
                return ((int)(this["cursorMagnetClippingExitDurationMs"]));
            }
            set {
                this["cursorMagnetClippingExitDurationMs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int cursorMagnetClippingChangeBoxIntoPerc {
            get {
                return ((int)(this["cursorMagnetClippingChangeBoxIntoPerc"]));
            }
            set {
                this["cursorMagnetClippingChangeBoxIntoPerc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public int cursorMagnetClippingMinBoxWidthMm {
            get {
                return ((int)(this["cursorMagnetClippingMinBoxWidthMm"]));
            }
            set {
                this["cursorMagnetClippingMinBoxWidthMm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1500")]
        public int mouseMovementEyeGazeResumeMilliseconds {
            get {
                return ((int)(this["mouseMovementEyeGazeResumeMilliseconds"]));
            }
            set {
                this["mouseMovementEyeGazeResumeMilliseconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int keyboardEyeGazeResumeMilliseconds {
            get {
                return ((int)(this["keyboardEyeGazeResumeMilliseconds"]));
            }
            set {
                this["keyboardEyeGazeResumeMilliseconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool zoomboxSticky {
            get {
                return ((bool)(this["zoomboxSticky"]));
            }
            set {
                this["zoomboxSticky"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public int zoomWindowPctScreen {
            get {
                return ((int)(this["zoomWindowPctScreen"]));
            }
            set {
                this["zoomWindowPctScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("350")]
        public int zoomWindowMagnificationPct {
            get {
                return ((int)(this["zoomWindowMagnificationPct"]));
            }
            set {
                this["zoomWindowMagnificationPct"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool zoomboxGrid {
            get {
                return ((bool)(this["zoomboxGrid"]));
            }
            set {
                this["zoomboxGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool zoomboxZoomAgain {
            get {
                return ((bool)(this["zoomboxZoomAgain"]));
            }
            set {
                this["zoomboxZoomAgain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900")]
        public int zoomboxZoomAgainAfterMs {
            get {
                return ((int)(this["zoomboxZoomAgainAfterMs"]));
            }
            set {
                this["zoomboxZoomAgainAfterMs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int fixationMinDurationMs {
            get {
                return ((int)(this["fixationMinDurationMs"]));
            }
            set {
                this["fixationMinDurationMs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int fixationRadiusClickAndHoldMm {
            get {
                return ((int)(this["fixationRadiusClickAndHoldMm"]));
            }
            set {
                this["fixationRadiusClickAndHoldMm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int fixationDurationClickAndHoldZoombox {
            get {
                return ((int)(this["fixationDurationClickAndHoldZoombox"]));
            }
            set {
                this["fixationDurationClickAndHoldZoombox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int fixationInitTimeClickAndHoldMs {
            get {
                return ((int)(this["fixationInitTimeClickAndHoldMs"]));
            }
            set {
                this["fixationInitTimeClickAndHoldMs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int fixationRadiusForHoverMm {
            get {
                return ((int)(this["fixationRadiusForHoverMm"]));
            }
            set {
                this["fixationRadiusForHoverMm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int fixationDurationForHoverMs {
            get {
                return ((int)(this["fixationDurationForHoverMs"]));
            }
            set {
                this["fixationDurationForHoverMs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int fixationMinCursorActiveMs {
            get {
                return ((int)(this["fixationMinCursorActiveMs"]));
            }
            set {
                this["fixationMinCursorActiveMs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cursorAlwaysFollowsGaze {
            get {
                return ((bool)(this["cursorAlwaysFollowsGaze"]));
            }
            set {
                this["cursorAlwaysFollowsGaze"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool fixationClickAndHoldEnabled {
            get {
                return ((bool)(this["fixationClickAndHoldEnabled"]));
            }
            set {
                this["fixationClickAndHoldEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool playGazeRecording {
            get {
                return ((bool)(this["playGazeRecording"]));
            }
            set {
                this["playGazeRecording"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hideCursorDuringGaze {
            get {
                return ((bool)(this["hideCursorDuringGaze"]));
            }
            set {
                this["hideCursorDuringGaze"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int precisionGazeMouseFormRefreshCount {
            get {
                return ((int)(this["precisionGazeMouseFormRefreshCount"]));
            }
            set {
                this["precisionGazeMouseFormRefreshCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool gazePointLoggingEnabled {
            get {
                return ((bool)(this["gazePointLoggingEnabled"]));
            }
            set {
                this["gazePointLoggingEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int largeSaccadeThresholdMm {
            get {
                return ((int)(this["largeSaccadeThresholdMm"]));
            }
            set {
                this["largeSaccadeThresholdMm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int calibrationCircleSizeMm {
            get {
                return ((int)(this["calibrationCircleSizeMm"]));
            }
            set {
                this["calibrationCircleSizeMm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int calibrationIterationTimeMs {
            get {
                return ((int)(this["calibrationIterationTimeMs"]));
            }
            set {
                this["calibrationIterationTimeMs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int calibrationIterationCountMax {
            get {
                return ((int)(this["calibrationIterationCountMax"]));
            }
            set {
                this["calibrationIterationCountMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19")]
        public int calibrationCompletedThresholdMm {
            get {
                return ((int)(this["calibrationCompletedThresholdMm"]));
            }
            set {
                this["calibrationCompletedThresholdMm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool dataCaptureEnabled {
            get {
                return ((bool)(this["dataCaptureEnabled"]));
            }
            set {
                this["dataCaptureEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public int dataCaptureSecondsToKeep {
            get {
                return ((int)(this["dataCaptureSecondsToKeep"]));
            }
            set {
                this["dataCaptureSecondsToKeep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool screenCaptureEnabled {
            get {
                return ((bool)(this["screenCaptureEnabled"]));
            }
            set {
                this["screenCaptureEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool automaticErrorNotification {
            get {
                return ((bool)(this["automaticErrorNotification"]));
            }
            set {
                this["automaticErrorNotification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool dockEnabled {
            get {
                return ((bool)(this["dockEnabled"]));
            }
            set {
                this["dockEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool dockFixateToSelectEnabled {
            get {
                return ((bool)(this["dockFixateToSelectEnabled"]));
            }
            set {
                this["dockFixateToSelectEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int dockButtonFixationMs {
            get {
                return ((int)(this["dockButtonFixationMs"]));
            }
            set {
                this["dockButtonFixationMs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int dockFormMaxWidthMm {
            get {
                return ((int)(this["dockFormMaxWidthMm"]));
            }
            set {
                this["dockFormMaxWidthMm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int dockButtonHeightMm {
            get {
                return ((int)(this["dockButtonHeightMm"]));
            }
            set {
                this["dockButtonHeightMm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool onscreenKeyboardEnabled {
            get {
                return ((bool)(this["onscreenKeyboardEnabled"]));
            }
            set {
                this["onscreenKeyboardEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int onscreenKeyWidthMm {
            get {
                return ((int)(this["onscreenKeyWidthMm"]));
            }
            set {
                this["onscreenKeyWidthMm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int onscreenKeyHeightMm {
            get {
                return ((int)(this["onscreenKeyHeightMm"]));
            }
            set {
                this["onscreenKeyHeightMm"] = value;
            }
        }
    }
}
